apiVersion: apps/v1
kind: Deployment
metadata:
  name: curd-app-db
  namespace: crud-app
  labels:
    app: curd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curd-app-db
  template:
    metadata:
      labels:
        app: curd-app-db
    spec:
      containers:
        - name: database
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"           
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: curd-app-db
  ports:
    - port: 5432
      targetPort: 5432